FROM java:8

# Set the WILDFLY_VERSION env variable
ENV WILDFLY_VERSION 8.2.0.Final


# Add files used for configuring wildfly
ADD install-wildfly-pom.xml /
ADD standalone.xml /
ADD module.xml /
ADD mysql-connector-java-5.1.30-bin.jar /

# Add the WildFly distribution to /opt, and make wildfly the owner of the extracted tar content
# Make sure the distribution is available from a well-known place
RUN cd / && curl http://download.jboss.org/wildfly/$WILDFLY_VERSION/wildfly-$WILDFLY_VERSION.tar.gz | tar zx && mv /wildfly-$WILDFLY_VERSION /wildfly

# Set the JBOSS_HOME env variable
ENV JBOSS_HOME /wildfly

RUN cp /standalone.xml /wildfly/standalone/configuration/
RUN mkdir -p /wildfly/modules/com/mysql/main
RUN cp /module.xml /wildfly/modules/com/mysql/main/
RUN cp /mysql-connector-java-5.1.30-bin.jar /wildfly/modules/com/mysql/main/
RUN chmod +x /wildfly/bin/*.sh

# Set up management port
RUN /wildfly/bin/add-user.sh ci "MANAGEMENT_PWD" --silent


# Expose the ports we're interested in
EXPOSE 8080
EXPOSE 9990

# Set the default command to run on boot
# This will boot WildFly in the standalone mode and bind to all interface
CMD ["/wildfly/bin/standalone.sh", "-b", "0.0.0.0", "-bmanagement", "0.0.0.0"]
